<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Store;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function persist(Store $store)
    {
        $this->getEntityManager()->persist($store);
        $this->getEntityManager()->flush($store);

        return $store;
    }
}
