AppBundle\Entity\Offer:
    type: entity
    table: offer
    repositoryClass: AppBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
        startAt:
            type: datetime
            nullable: false
        endAt:
            type: datetime
            nullable: false
        body:
            type: string
            length: 255
            nullable: false
    manyToMany:
        pictures:
            targetEntity: AppBundle\Entity\Picture
            joinTable:
                name: offer_picture_rel
                joinColumns:
                    offer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    picture_id:
                        referencedColumnName: id
                        unique: true
