AppBundle\Entity\Store:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StoreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
