AppBundle\Entity\Store:
    type: entity
    table: store
    repositoryClass: AppBundle\Repository\StoreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    manyToMany:
        # A store has N offers with a relationship table.
        # Unidirectional: can be access only from company to offer.
        offers:
            targetEntity: AppBundle\Entity\Offer
            joinTable:
                name: company_offer_rel
                joinColumns:
                    company_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    offer_id:
                        referencedColumnName: id
                        unique: true
